name: Scan for Sensitive Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan for secrets
        uses: github/security-code-scanning-action@v1
