name: Scan for Sensitive Data

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Search for sensitive data patterns
        run: |
          # Simple regex to detect potential sensitive data like API keys
          echo "Scanning for potential sensitive data..."
          grep -r -E "AWS_ACCESS_KEY|SECRET_KEY|API_KEY|PASSWORD|TOKEN" . >> scan_results.txt
      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: scan_results.txt
