name: CodeQL Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read  # Required to read code from the repository
  security-events: write  # Required to create and update security alerts

jobs:
  codeql:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed to access code
      security-events: write  # Needed to upload results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2  # Correct action reference for setup

      - name: Build CodeQL database
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

      - name: Upload CodeQL results
        uses: github/codeql-action/upload-sarif@v2
